### PR TITLE
_feature/create-generate_align_parameters-script

### PR DESCRIPTION
**Pull request by cfrick13**
- this code computes the alignment parameters to align each scene across the multiple rounds of imaging
- should take a barcode as an argument,
- then this code reads that dataframe pickle for that given barcode
- then it uses the dataframe to determine the reference channel to be used for each of the rounds for 
- then it loads all the reference channel images for each round
- then it runs the an alignment algorithm to align all of the rounds 
-  all positions should be aligned to round 1 (that will be the reference round)
-  this will enable all the processing to be run in stages later on as new data is acquired

### CODE REVIEW

**Review by BrianWhitneyAI — COMMENTED** [review]
Looks like a good starting point!

**Review by gouthamr321 — COMMENTED** [review]
looks good

**Review by aditnath — COMMENTED** [review]
Looks good! we may want to add typings to al functions (what are the types of all the inputs and outputs), as this will help in the future to create pipelines and use snakemake

**Comment by cfrick13** [comment]
the code I added `example_alignment_testing_script.py` details how the image translation for alignment is done and exports these figures as visualization. This code can be used to benchmark any new alignment script development. 


5500000724_example_fig_alignment_points

5500000724_example_fig_alignment_result

5500000724_example_fig_auto_alignment_result

**Comment by cfrick13** [comment]
This PR also rewrote the second half of  `4i_align_export_from_pickle.py`  into a new function for executing the alignment called `exectue_round_alignment.py`

**Review by aditnath — APPROVED** [review]

**Review by BrianWhitneyAI — APPROVED** [review]
looks good for the baseline. ready for cleanup!

**Pull request merged**
