### PR TITLE
validate basic functions of all python scripts

### PR DESCRIPTION
**Pull request by cfrick13**
this PR is aimed at validating all basic functions of the python scripts in this repo.

After this PR is merged to main, we should have a validated set of scripts that are functional to fall back on.

### CODE REVIEW

**Comment by cfrick13** [comment]
OK. I did a lot in this PR. 

- I changed where the yaml files get stored so that they are not in the code directory but in an output_path directory specified by the user, which is where all the processed image data will then get stored. 
- I started a readme file section to document how to run the code in the command line
- I changed variable names to be compatible with the config file naming changes done by @gouthamr321 
- I created scripts that produce outputs to check the dataframes that are created at different steps. This should help the user know if their dataframes are weird or not. 

an example is shown here:
image

- I also created a separate script for collecting the image metadata from the parent czi files. 
- then I did a lot in one commit that cleaned up the code to generate the matched dataframe and then also created a script to check that dataframe for more needed cleaning (i.e. to remove the positions that overlap multiple times with other positions in an intelligent way based on the acqusition time and whether that position has been previously flagged. This is the file `filter_matched_position_dataframe_to_remove_multiple_matches.py`
- then I cleaned up code to generate alignment parameters and execute the round alignment
- I also corrected a few details (like loading csvs instead of pickles) to enable the files to run on slurm
- and then I checked the code with `mypy`

**Comment by cfrick13** [comment]
the code for producing check outputs on the dataframes are
`check_parent_image_metadata_dataframe.py` and `check_matched_position_dataframe.py`

**Comment by cfrick13** [comment]
I also tried to leave helpful commments here and there along the way :)

**Comment by cfrick13** [comment]
here is an example of barcode 725.
first get metadata by running `gather_parent_image_metadata.py`
then run  `check_parent_image_metadata_dataframe.py`  and get this output:
image

then run `generate_matched_position_dataframe.py`, followed by `filter_matched_position_dataframe_to_remove_multiple_matches.py`.

Then run `check_matched_position_dataframe.py` to get this output check:
image

**Comment by cfrick13** [comment]
@BrianWhitneyAI @aditnath @gouthamr321 this is ready for review

**Comment by cfrick13** [comment]
need to add the following eventually (not necessarily within this branch):

- find camera aligned ome tiff images
- add try except line to allow some positions to fail alignment. and record in dataframe when alignment fails. 
- add ability to save out processing into a testing folder (perhaps...call it `aligned_4i_exports_{testingname}`)
- determine what crop size to use and adjust so that code doesn't take so long
- don't save images using skimage [find a better package?]
- develop jinja template to submit processing to slurm on a position by position basis. (for compute alignment parameters and for execute alignment)
- need to revisit the question of how to save the alignned images and how to name them (be sure to check if they have unique filenames). Maybe you should write this as its own script and generate a dataframe with all the save names that will be generated. 
- AND add ability to export "unaligned" images so that you can make contact sheets of what lack of alignment looks like easily. 
-

**Review by gouthamr321 — COMMENTED** [review]
Should we hardcode the final shape here? I'm thinking these might be better if we make this a function of the image dimensions maybe?

**Review by BrianWhitneyAI — APPROVED** [review]

**Comment by cfrick13** [comment]
> Should we hardcode the final shape here? I'm thinking these might be better if we make this a function of the image dimensions maybe?

we definitely should loop back and do this. I will add it to the future work issues page

**Pull request merged**
