### PR TITLE
improve robustness of current alignment algorithm

### PR DESCRIPTION
**Pull request by cfrick13**
The alignment algorithm failed on barcode 5500000724 p9. I will investigate why and make changes to improve the robustness so that all positions can be processed efficiently and quickly without any errors killing the code.

### CODE REVIEW

**Comment by cfrick13** [comment]
Next step will be to write a check that reports back on what positions failed alignment. Currently they will be attempted to be "aligned" but just using a 0,0,0 offset. 
And also to submit individual alignment jobs for each position on slurm.

**Comment by cfrick13** [comment]
the memory limit is exceeded at p34 or p35 during `generate_alignment_paramters`
even though I've given slurm 70GB of RAM
```
POSITION =  P34
srun: Exceeded job memory limit
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: n182: task 0: Killed
chris.frick@n232:~$
```

slurm was initialized with this :
```srun -p aics_cpu_general --mem 70G --pty bash #
module load anaconda3
source activate frick_multiplex
cd //allen/aics/assay-dev/users/Frick/PythonProjects/Assessment/4iProcessing-/
```

**Comment by cfrick13** [comment]
execute alignment failed at 5500000724 p15 round6
```

[9.0, -54.6, 148.2]
Round 6
[-11.0, -60.6, -10.6]
<class 'list'>
Traceback (most recent call last):
  File "/allen/aics/assay-dev/users/Frick/PythonProjects/Assessment/4iProcessing-/./multiplex_immuno_processing/exectue_round_alignment.py", line 180, in <module>
    imgstack = delayed_chunk.compute()
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/base.py", line 315, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/base.py", line 598, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/threaded.py", line 89, in get
    results = get_async(
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/local.py", line 319, in reraise
    raise exc
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/utils.py", line 71, in apply
    return func(*args, **kwargs)
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/aicsimageio/readers/czi_reader.py", line 281, in _read_chunk_from_image
    return CziReader._get_image_data(
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/aicsimageio/readers/czi_reader.py", line 330, in _get_image_data
    data, dims = czi.read_image(**read_dims)
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/aicspylibczi/CziFile.py", line 552, in read_image
    image, shape = self.reader.read_selected(plane_constraints, m_index, cores)
_aicspylibczi.PylibCZI_CDimCoordinatesOverspecifiedException: The coordinates are overspecified = you have specified a Dimension or Dimension value that is not valid. S value 28invalid, ∉ [0, 16)

```

**Comment by cfrick13** [comment]
this code runs in my windows environment but not my linux (slurm-based) environment
```
import os
from aicsimageio import AICSImage
filename = '//allen/aics/microscopy/Antoine/Analyse EMT/4i Data/5500000724/ZSD1/Round 6/5500000724_Round_6_20X_P1_to_P16.czi'
print(os.path.abspath(filename))

reader = AICSImage(filename)
T=0
ci=0
delayed_chunk = reader.get_image_dask_data("ZYX", T=T, C=ci)
reader.set_scene(14)
print(reader.current_scene)

print(reader.current_scene_index)

imgstack = delayed_chunk.compute()

print(imgstack.shape)
```

ERROR MESSAGE:
```
Traceback (most recent call last):
  File "/allen/aics/assay-dev/users/Frick/PythonProjects/Assessment/4iProcessing-/./multiplex_immuno_processing/exectue_round_alignment.py", line 180, in <module>
    imgstack = delayed_chunk.compute()
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/base.py", line 315, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/base.py", line 598, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/threaded.py", line 89, in get
    results = get_async(
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/local.py", line 319, in reraise
    raise exc
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/dask/utils.py", line 71, in apply
    return func(*args, **kwargs)
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/aicsimageio/readers/czi_reader.py", line 281, in _read_chunk_from_image
    return CziReader._get_image_data(
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/aicsimageio/readers/czi_reader.py", line 330, in _get_image_data
    data, dims = czi.read_image(**read_dims)
  File "/allen/aics/apps/hpc_shared/mod/anaconda3-5.3.0/envs/frick_multiplex/lib/python3.9/site-packages/aicspylibczi/CziFile.py", line 552, in read_image
    image, shape = self.reader.read_selected(plane_constraints, m_index, cores)
_aicspylibczi.PylibCZI_CDimCoordinatesOverspecifiedException: The coordinates are overspecified = you have specified a Dimension or Dimension value that is not valid. S value 28invalid, ∉ [0, 16)
```

windows environment (python 3.8.12)
```
aicsfiles==5.0.0.dev16
aicsimageio==4.6.3
aicspylibczi==3.0.5
aicssegmentation==0.4.2
alabaster==0.7.12
anyio==3.5.0
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asciitree==0.3.3
asttokens==2.0.5
attrs==21.4.0
aws-requests-auth==0.4.3
Babel==2.9.1
backcall==0.2.0
backoff==1.11.1
beautifulsoup4==4.10.0
bleach==4.1.0
boto3==1.24.39
botocore==1.27.39
cachey==0.2.1
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
click==8.0.4
cloudpickle==2.0.0
colorama==0.4.4
colorcet==3.0.0
cycler==0.11.0
dask==2022.2.1
debugpy==1.5.1
decorator==5.1.1
defusedxml==0.7.1
dnspython==2.2.1
docstring-parser==0.13
docutils==0.17.1
elementpath==2.5.0
email-validator==1.1.3
entrypoints==0.4
executing==0.8.3
fasteners==0.17.3
fonttools==4.31.1
freetype-py==2.2.0
fsspec==2022.2.0
HeapDict==1.0.1
hsluv==5.0.2
idna==3.3
imagecodecs==2022.2.22
imageio==2.16.1
imageio-ffmpeg==0.4.7
imagesize==1.3.0
importlib-metadata==4.11.3
importlib-resources==5.4.0
ipydatawidgets==4.2.0
ipykernel==6.9.2
ipympl==0.8.8
ipython==8.1.1
ipython-genutils==0.2.0
ipywidgets==7.7.0
itk==5.2.1.post1
itk-core==5.2.1.post1
itk-filtering==5.2.1.post1
itk-io==5.2.1.post1
itk-meshtopolydata==0.7.1
itk-numerics==5.2.1.post1
itk-registration==5.2.1.post1
itk-segmentation==5.2.1.post1
itkwidgets==0.32.1
jedi==0.18.1
Jinja2==3.0.3
jmespath==1.0.1
json5==0.9.6
jsonlines==1.2.0
jsonschema==4.4.0
jupyter==1.0.0
jupyter-client==7.1.2
jupyter-console==6.4.3
jupyter-core==4.9.2
jupyter-server==1.15.6
jupyterlab==3.3.2
jupyterlab-pygments==0.1.2
jupyterlab-server==2.11.2
jupyterlab-widgets==1.1.0
kiwisolver==1.4.0
labkey==1.4.1
lkaccess==1.4.25
locket==0.2.1
lxml==4.8.0
magicgui==0.3.7
MarkupSafe==2.1.1
matplotlib==3.5.1
matplotlib-inline==0.1.3
mistune==0.8.4
mypy==0.971
mypy-extensions==0.4.3
napari==0.4.15
napari-console==0.0.4
napari-plugin-engine==0.2.0
napari-svg==0.1.6
nbclassic==0.3.7
nbclient==0.5.13
nbconvert==6.4.4
nbformat==5.2.0
nest-asyncio==1.5.4
networkx==2.7.1
notebook==6.4.10
notebook-shim==0.1.0
npe2==0.2.1
numcodecs==0.9.1
numpy==1.22.3
numpydoc==1.2
ome-types==0.2.10
opencv-python==4.5.5.64
packaging==21.3
pandas==1.4.1
pandocfilters==1.5.0
param==1.12.0
parso==0.8.3
partd==1.2.0
pickleshare==0.7.5
Pillow==9.0.1
Pint==0.18
pooch==1.6.0
prometheus-client==0.13.1
prompt-toolkit==3.0.28
psutil==5.9.0
psygnal==0.3.3
pure-eval==0.2.2
pyaml==20.4.0
pycparser==2.21
pyct==0.4.8
pydantic==1.9.0
Pygments==2.11.2
PyOpenGL==3.1.6
pyparsing==3.0.7
PyQt5==5.15.6
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.1
pyrsistent==0.18.1
python-dateutil==2.8.2
pytomlpp==1.0.10
pytz==2021.3
PyWavelets==1.3.0
pywin32==303
pywinpty==2.0.5
PyYAML==6.0
pyzmq==22.3.0
qtconsole==5.2.2
QtPy==2.0.1
quilt3==5.0.0
requests==2.27.1
requests-futures==1.0.0
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.6
s3transfer==0.6.0
scikit-image==0.19.2
scipy==1.8.0
Send2Trash==1.8.0
six==1.16.0
sniffio==1.2.0
snowballstemmer==2.2.0
soupsieve==2.3.1
Sphinx==4.4.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
stack-data==0.2.0
superqt==0.3.1
tenacity==8.0.1
terminado==0.13.3
testpath==0.6.0
tifffile==2022.3.16
tomli==2.0.1
toolz==0.11.2
tornado==6.1
tqdm==4.63.0
traitlets==5.1.1
traittypes==0.2.1
typer==0.4.0
typing_extensions==4.1.1
urllib3==1.26.9
vispy==0.9.6
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.3.1
widgetsnbextension==3.6.0
wrapt==1.14.0
xarray==2022.3.0
xmlschema==1.10.0
zarr==2.11.1
zipp==3.7.0
zstandard==0.17.0
```

slurm_environment (python = 3.9.12)
```
aicsfiles==5.0.0.dev21
aicsimageio==4.9.1
aicspylibczi==3.0.5
asciitree==0.3.3
backoff==1.11.1
certifi @ file:///opt/conda/conda-bld/certifi_1655968806487/work/certifi
charset-normalizer==2.1.0
cloudpickle==2.1.0
cycler==0.11.0
dask==2022.8.0
dnspython==2.2.1
elementpath==2.5.3
email-validator==1.2.1
entrypoints==0.4
fasteners==0.17.3
fonttools==4.36.0
fsspec==2022.7.1
idna==3.3
imagecodecs==2022.8.8
imageio==2.21.1
kiwisolver==1.4.4
labkey==1.4.1
lkaccess==1.4.25
locket==1.0.0
lxml==4.9.1
matplotlib==3.5.3
networkx==2.8.5
numcodecs==0.10.2
numpy==1.23.2
ome-types==0.3.0
opencv-python==4.6.0.66
packaging==21.3
pandas==1.4.3
partd==1.3.0
Pillow==9.2.0
Pint==0.19.2
pyaml==20.4.0
pydantic==1.9.2
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.2.1
PyWavelets==1.3.0
PyYAML==6.0
requests==2.28.1
resource-backed-dask-array==0.1.0
scikit-image==0.19.3
scipy==1.9.0
six==1.16.0
tifffile==2022.8.12
toolz==0.12.0
typing_extensions==4.3.0
urllib3==1.26.11
wrapt==1.14.1
xarray==2022.6.0
xmlschema==1.11.3
zarr==2.12.0
```

**Comment by cfrick13** [comment]
see this github issue for more discussion about why AICSImage is failing at this one position
https://github.com/AllenCellModeling/aicsimageio/issues/430

**Comment by cfrick13** [comment]
to get around the error above you can use an earlier version of aicsimageio. This requires some weirdness to install tho
```
pip uninstall aicsimageio
pip install aicsimageio~=4.7.0

pip uninstall fsspec
pip install fsspec=2022.05.0
```

**Comment by cfrick13** [comment]
ok. I think this is ready to be merged. (@gouthamr321 let me know if you want a call to discuss changes)

**Comment by cfrick13** [comment]
Summary: this branch is a mountain of changes.

- big change is renaming all dataframe save paths from `alignment_pickles_each` to `alignment_csvs_each_{alignment_method}`. Other paths with pickle in the name were also changed. 
- the changes here also make it recorded whether a position failed alignment within the saved dataframe. 
- it also removes the option to compute alignment with both methods. It makes you choose one or the other. (mainly due to issue with how to read a dataframe with alignment results if there are two alignment offsets in it...should be simple to fix...just not time to fix it right now)
- this also renames files with typos in their names
-

**Review by gouthamr321 — APPROVED** [review]

**Pull request merged**
